#include "unity.h"
#include "SPI.h"

void setUp(void)
{
	UCA0CTLW0 = 0;
	UCA0BRW = 0;
	UCA0MCTLW = 0;
	UCA0IE = 0;
	UCA1IE = 0;
	UCB0IE = 0;
}

void tearDown(void)
{
}



void test_SPI_Master_3W_Init_should_AcceptValidInputs(void)
{
	/* Test General Conditions */
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A0,0,0,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A0,0,0,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A1,250000,1000000,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_B0,1000000,8000000,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_B0,8000000,8000000,UCSSEL__ACLK));
	
	/* Test Different Valid Ports and Clocks */
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A0,0,0,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A1,0,0,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_B0,0,0,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A0,0,0,UCSSEL__SMCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A1,0,0,UCSSEL__SMCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_B0,0,0,UCSSEL__SMCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A0,0,0,UCSSEL__UCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A1,0,0,UCSSEL__UCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_B0,0,0,UCSSEL__UCLK));
	
	
	/* Test Different Valid Ports & Clocks and Frequencies */
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A0,1000000,8000000,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A1,1000000,8000000,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_B0,1000000,8000000,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A0,1000000,8000000,UCSSEL__SMCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A1,1000000,8000000,UCSSEL__SMCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_B0,1000000,8000000,UCSSEL__SMCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A0,1000000,8000000,UCSSEL__UCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_A1,1000000,8000000,UCSSEL__UCLK));
	TEST_ASSERT_EQUAL(0,SPI_Master_3W_Init(SPI_B0,1000000,8000000,UCSSEL__UCLK));
}

void test_SPI_Master_3W_Init_should_RejectInvalidInputs(void)
{
	/* Reject Bad Ports */
	TEST_ASSERT_EQUAL(1,SPI_Master_3W_Init(3,0,0,UCSSEL__SMCLK));
	TEST_ASSERT_EQUAL(1,SPI_Master_3W_Init(255,0,0,UCSSEL__SMCLK));
	
	/* Reject Bad CLKS */
	TEST_ASSERT_EQUAL(1,SPI_Master_3W_Init(0,0,0,0x00FF));
	TEST_ASSERT_EQUAL(1,SPI_Master_3W_Init(0,0,0,0x0010));
	
	/* Reject Bit Rates Higher than Clk Freq */
	TEST_ASSERT_EQUAL(1,SPI_Master_3W_Init(SPI_A0,2000000,1000000,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(1,SPI_Master_3W_Init(SPI_A0,8000000,4000000,UCSSEL__ACLK));
	TEST_ASSERT_EQUAL(1,SPI_Master_3W_Init(SPI_A0,16000000,8000000,UCSSEL__ACLK));
}

void test_SPI_Master_3W_Init_should_SetCorrectRegisters(void)
{
	
	
}



void test_SPI_Master_EnableInterrupts_should_AcceptValidPorts(void)
{
	TEST_ASSERT_EQUAL(0,SPI_Master_EnableInterrupts(SPI_A0,true,true));
	TEST_ASSERT_EQUAL(0,SPI_Master_EnableInterrupts(SPI_A1,true,true));
	TEST_ASSERT_EQUAL(0,SPI_Master_EnableInterrupts(SPI_B0,true,true));
}

void test_SPI_Master_EnableInterrupts_should_RejectInvalidPorts(void)
{
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(3,false,false));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(127,false,false));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(255,false,false));
}

void test_SPI_Master_EnableInterrupts_should_RejectInvalidInterruptValues(void)
{
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(SPI_A0,2,false));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(SPI_A0,false,2));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(SPI_A0,255,false));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(SPI_A0,false,255));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(SPI_A0,2,true));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(SPI_A0,true,2));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(SPI_A0,255,true));
	TEST_ASSERT_EQUAL(1,SPI_Master_EnableInterrupts(SPI_A0,true,255));
	
}

void test_SPI_Master_EnableInterrupts_should_SetValidInterrupts(void)
{
	TEST_ASSERT_EQUAL(0,SPI_Master_EnableInterrupts(SPI_A0,false,false));
	TEST_ASSERT_EQUAL(0,UCA0IE);
	

	
}



/********************* Test SPI_putc ********************************/
void test_SPI_putc_should_AcceptValidPorts(void)
{
	
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x00,SPI_A0));
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x00,SPI_A1));
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x00,SPI_B0));
	
}

void test_SPI_putc_should_RejectInvalidPorts(void)
{
	
	TEST_ASSERT_EQUAL(SPI_FAIL,SPI_putc(0x00,32));
	TEST_ASSERT_EQUAL(SPI_FAIL,SPI_putc(0x00,127));
	TEST_ASSERT_EQUAL(SPI_FAIL,SPI_putc(0x00,255));
}

void test_SPI_putc_should_TransmitOnCorrectChannel(void)
{
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x00,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(0,UCA0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0xFF,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(0xFF,UCA0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x7A,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(0x7A,UCA0TXBUF);
	
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x00,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(0,UCA1TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x1E,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(0x1E,UCA1TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0xCD,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(0xCD,UCA1TXBUF);
	
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x00,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(0,UCB0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0x27,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(0x27,UCB0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_putc(0xFB,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(0xFB,UCB0TXBUF);
}



/********************* Test SPI_puts ********************************/
void test_SPI_puts_ShouldAcceptValidPorts(void)
{
	uint8_t values[] = {0,5,25,32,173,251};
	
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_A0));
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_A1));
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_B0));
	
}


void test_SPI_should_RejectInvalidPorts(void)
{
	uint8_t values[] = {0,5,25,32,173,251};
	
	TEST_ASSERT_EQUAL(SPI_FAIL,SPI_puts(&values[0],6,27));
	TEST_ASSERT_EQUAL(SPI_FAIL,SPI_puts(&values[0],6,5));
	TEST_ASSERT_EQUAL(SPI_FAIL,SPI_puts(&values[0],6,255));
}


void test_SPI_puts_should_TransmitOnCorrectChannel(void)
{
	uint8_t values[] = {0,5,25,32,173,251};
	
	
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(251,UCA0TXBUF);
	
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(251,UCA1TXBUF);
	
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(251,UCB0TXBUF);
}

void test_SPI_puts_should_TransmitFullString(void)
{
	
	uint8_t values[] = {0,5,25,32,173,251};
	
	/*  SPI_A0  */
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],1,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(0,UCA0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],2,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(5,UCA0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],3,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(25,UCA0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],4,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(32,UCA0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],5,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(173,UCA0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_A0));
	TEST_ASSERT_EQUAL_HEX8(251,UCA0TXBUF);
	
	/*  SPI_A1  */
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],1,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(0,UCA1TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],2,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(5,UCA1TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],3,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(25,UCA1TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],4,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(32,UCA1TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],5,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(173,UCA1TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_A1));
	TEST_ASSERT_EQUAL_HEX8(251,UCA1TXBUF);
	
	/*  SPI_B0  */
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],1,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(0,UCB0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],2,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(5,UCB0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],3,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(25,UCB0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],4,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(32,UCB0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],5,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(173,UCB0TXBUF);
	TEST_ASSERT_EQUAL(SPI_OK,SPI_puts(&values[0],6,SPI_B0));
	TEST_ASSERT_EQUAL_HEX8(251,UCB0TXBUF);
	
	
}